version: '3.7'
services:
  pg:
    image: 'postgres:14-alpine'
    container_name: 'authkun-database'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: authkun
      NODE_ENV: dev
    ports:
      - '5433:5432'
    volumes:
      - ./src/scripts/createDb.sh:/docker-entrypoint-initdb.d/createDb.sh
